#!/bin/bash

set -o pipefail
# set -e -> exit if any command has a non-zero exit status
# set -u -> reference to any undefined variable is an error
# set -x -> print all executed commands to the terminal
# set -o pipefail -> prevents errors in a pipeline from being masked


# rctl version
#-------------------------------------------------------------------------------

g_version_major=2


# config
#-------------------------------------------------------------------------------

if [[ -z $XDG_CONFIG_HOME ]]; then
	# for mac os
	XDG_CONFIG_HOME="$HOME/.config"
fi

if [[ -z $EDITOR ]]; then
	EDITOR="vi"
fi

g_rctl="$(basename "$0")"
g_main_rctl="$XDG_CONFIG_HOME/rctl"
g_main_cmd_dir="$g_main_rctl/cmd" # global commands
g_main_hooks_dir="$g_main_rctl/hooks" # global hooks
g_main_version="$g_main_rctl/.version" # global version
g_main_config="$g_main_rctl/rctl.env" # global config

g_project_rctl=".rctl"
g_project_rctl_gitignore_grep="^/\.rctl(\$|/)"
g_project_rctl_gitignore=( \
	"/.rctl/cmd/local/*.bash" \
	"/.rctl/hooks/local/*.bash" \
	"/.rctl/param.env" \
)
g_project_cmd_dir="$g_project_rctl/cmd"
g_project_hooks_dir="$g_project_rctl/hooks"
g_project_version="$g_project_rctl/.version"
g_project_param="$g_project_rctl/param.env"
g_project_setup="$g_project_rctl/setup.env"

g_project_root_hints=("$g_project_setup")
g_initializable_root_hints=(".git")

g_rsync_opts="--recursive --executability --copy-links --delete -zz"


# library
#-------------------------------------------------------------------------------

OK=0
ERR=1

err_not_project="not in an project (use \`$g_rctl init\` to initialize)"
err_not_initializable="not in an initializable project (requires ${g_initializable_root_hints[@]})"

# no operation
_() {
	echo -n
}

throw() {
	local mesg="$1"

	echo -e "error: $mesg" >&2

	exit $ERR
}

task_head() {
	local task_name="$(echo "$1" | perl -pe 's/ +/_/g')"
	local progress_start="$2"

	echo -ne "task \e[97;1m${task_name}\e[0m {\n\e[90m"

	if [[ -n "$progress_start" ]]; then
		echo "    $progress_start"
	fi
}

task_end() {
	local progress_end="$1"

	if [[ -n "$progress_end" ]]; then
		echo "$progress_end"
	fi

	echo -e "\e[0m}\n"
}

task() {
	local task_name="$(echo "$1" | perl -pe 's/ +/_/g')"
	local task_cmd=("${@:2}")

	# execute in a separate unit so we don't mess with the cwd
	(
		if [[ "${task_cmd[0]}" == "--cwd" ]]; then
			if [[ -z "${task_cmd[1]}" || ! -d "${task_cmd[1]}" ]]; then
				throw "invalid directory: ${${task_cmd[1]-"unknown"}}"
			fi

			cd "${task_cmd[1]}"
			task_cmd=("${task_cmd[@]:2}")
		fi

		task_head "$task_name"

		echo -ne "\e[90m"
		"${task_cmd[@]}" 2>&1 | sed 's/^/    /' && echo -e "\e[0m}\n" \
			|| { task_end; throw "task '${task_name}' failed"; }

	) || exit 1
}

info() {
	local mesg="$1"
	#echo -e "\e[94m* ${mesg}\e[0m"
}

in_array() {
	local entry match="$1"
	shift
	# for without a list iterates over the argument list
	for entry; do
		[[ $entry == $match ]] && return $OK
	done
	return $ERR
}

detect_root() {
	local hints=("$@")
	local path="$PWD"

	for hint in "${hints[@]}"; do
		if [[ -e "$path/$hint" ]]; then
			return $OK
		fi
	done

	return $ERR
}

find_root() {
	local hints=("$@")
	local path="$PWD"
	local parent=""

	(
		cd "$path"

		while true; do
			if detect_root "${hints[@]}"; then
				echo "$PWD"
				return $OK
			fi

			if [[ $PWD == $parent ]]; then
				return $ERR
			fi

			parent="$PWD"
			cd ..
		done
	)
}

find_project_root() {
	find_root "${g_project_root_hints[@]}"
}

find_initializable_root() {
	find_root "${g_initializable_root_hints[@]}"
}

in_project() {
	find_project_root >/dev/null
}

in_initializable_project() {
	find_initializable_root >/dev/null
}

list_commands() {
	local basedir="$1"

	if [[ -d $basedir ]]; then
		ls -1 "$basedir" | sed 's/\.bash//' | while read cmd; do
			if [[ -f "$basedir/$cmd.bash" && ! $cmd =~ ^[_.] ]]; then
				echo "$cmd"
			fi
		done
	fi
}

run_global_hook_if_exists() {
	local cmd="$1"
	local at="$2"

	if [[ $at != "before" && $at != "after" ]]; then
		throw "[fatal] hook moments must be before or after"
	fi

	if [[ -z $cmd ]]; then
		throw "[fatal] command parameter is required"
	fi

	hook="$g_main_hooks_dir/${cmd}.${at}.bash"

	if [[ -f $hook ]]; then
		info "running global hook: $at $cmd"
		source "$hook"
	fi
}

run_project_hook_if_exists() {
	local cmd="$1"
	local at="$2"

	if [[ $at != "before" && $at != "after" ]]; then
		throw "[fatal] hook moments must be before or after"
	fi

	if [[ -z $cmd ]]; then
		throw "[fatal] command parameter is required"
	fi

	local project="$(find_project_root)"

	if [[ -n $project ]]; then
		hook="$project/$g_project_hooks_dir/${cmd}.${at}.bash"

		if [[ -f $hook ]]; then
			info "running project hook: $at $cmd"
			source "$hook" || exit $ERR
		fi
	fi
}

edit() {
	local file="$1"

	(
		source "$g_main_config"
		"$editor" "$file"
	)
}

project_list_targets() {
	if ! in_project; then
		throw "$err_not_project"
	fi

	(
		local project="$(find_project_root)"
		local project_rctl="$project/$g_project_rctl"

		cd "$project" # required for rsync
		source "$(find_project_root)/$g_project_setup"

		for target in "${targets[@]}"; do
			echo "$target"
		done
	)
}

project_has_target() {
	local target="$1"
	local project_target

	for project_target in $(project_list_targets); do
		if [[ $project_target == $target ]]; then
			return $OK
		fi
	done

	return $ERR
}

usage() {
	local cmd="$1"
	local main_cmd="$(list_commands "$g_main_cmd_dir")"
	local project="$(find_project_root)"
	local project_cmd=""

	local project_cmd_dir="$projects/$g_project_cmd_dir"
	local project_cmd_dir="$projects/$g_project_cmd_dir"

	if in_project; then
		project_cmd="$(list_commands "$project_cmd_dir")"
	fi

	if [[ -n $cmd ]]; then
		if in_project; then
			for test_cmd in $project_cmd; do
				if [[ $test_cmd == $cmd ]]; then
					project="$(find_project_root)"
					project_rctl="$project/$g_project_rctl"
					cmd_file="$project_cmd_dir/${cmd}.bash"
					echo -n "rctl ${cmd} "
					source "$(find_project_root)/$g_project_setup"
					source "$cmd_file"
					command_usage "$@"
					exit $?
				fi
			done
		fi

		for test_cmd in $main_cmd; do
			if [[ $test_cmd == $cmd ]]; then
				cmd_file="$g_main_cmd_dir/${cmd}.bash"
				echo -n "rctl ${cmd} "
				source "$cmd_file"
				command_usage "$@"
				exit $?
			fi
		done

		throw "invalid command"
	fi

	echo "rctl: remote control for your projects"
	echo
	echo "usage: rctl <cmd> [<args...>]"
	echo
	echo "built-in commands:"
	echo
	if ! in_project && in_initializable_project; then
		echo "    init"
		echo "        initialize rctl in a git project (in the current working directory)"
	fi
	if in_project; then
		echo "    ssh <target>"
		echo "        ssh to target"
		echo
		echo "    push <target>"
		echo "        deploy current project to the target"
		echo
		echo "    .edit-cmd <cmd>"
		echo "        edit a custom project command"
		echo
		echo "    .edit-hook {before|after} <cmd>"
		echo "        edit (or create) a hook {pre|post}-<cmd>"
		echo
		echo "    .param"
		echo "        edit project parameters"
		echo
		echo "    .setup"
		echo "        edit project setup"
		echo
	fi
	echo "    .help [<custom_cmd>]"
	echo "        print this help (or help about the specified custom command)"

	if [[ -n $project_cmd ]]; then
		echo
		echo "project-specific commands:"
		echo
		for cmd in $project_cmd; do
			project="$(find_project_root)"
			project_rctl="$project/$g_project_rctl"
			cmd_file="$project_cmd_dir/${cmd}.bash"
			source "$(find_project_root)/$g_project_setup"
			source "$cmd_file"
			echo "    $cmd $(command_usage "$@" | perl -pe 's/^/    /g' | sed '1s/^    //')"
			echo
		done
	fi

	if [[ -n $main_cmd ]]; then
		echo
		echo "global custom commands:"
		echo
		for cmd in $main_cmd; do
			cmd_file="$g_main_cmd_dir/${cmd}.bash"
			source "$cmd_file"
			echo "    $cmd $(command_usage "$@" | perl -pe 's/^/    /g' | sed '1s/^    //')"
			echo
		done
	fi

	#echo "edit your global setup in: $g_main_rctl"
}

check_version() {
	if [[ -d $g_main_rctl ]]; then
		if [[ ! -f $g_main_version || "$(cat "$g_main_version")" -ne "$g_version_major" ]]; then
			throw "you have an old version of rctl installed in your home.\nplease manually upgrade \`$g_main_rctl\` to version $g_version_major"
		fi
	fi

	if in_project; then
		local project="$(find_project_root)"
		local project_version="$project/$g_project_version"

		if [[ ! -f "$project_version" || "$(cat "$project_version")" -ne "$g_version_major" ]]; then
			throw "you have an old version of rctl installed in this project.\nplease manually upgrade $project to version $g_version_major"
		fi
	fi
}

rctl_setup() {
	if [[ ! -d $g_main_rctl ]]; then
		mkdir -p "$g_main_rctl"
		mkdir "$g_main_cmd_dir"
		mkdir "$g_main_hooks_dir"

		touch "$g_main_config"
		echo "$g_version_major" > "$g_main_version"

		(
			echo "editor=\"$EDITOR\""
			echo
			echo "# note: keep the quotes"
			echo "default_sync_include='(\"*\")'"
			echo "default_sync_exclude='()'"
			echo "default_target=\"live\""
			echo "default_target_host='\"\"'"
			echo "default_target_user='\"\"'"
			echo "default_target_dir='\"\"'"
		) >> "$g_main_config"
	fi

	if [[ ! -f $g_main_config ]]; then
		throw "invalid configuration directory: $g_main_rctl"
	fi
}


# commands
#-------------------------------------------------------------------------------

project_init() {
	local project

	if ! in_initializable_project; then
		throw "$err_not_initializable"
	fi

	if in_project; then
		throw "this project has already been initialized"
	fi

	project="$(find_initializable_root)"

	local project_rctl="$project/$g_project_rctl"
	local project_gitignore="$project/.gitignore"

	local project_cmd_dir="$project/$g_project_cmd_dir"
	local project_hooks_dir="$project/$g_project_hooks_dir"
	local project_version="$project/$g_project_version"
	local project_param="$project/$g_project_param"
	local project_setup="$project/$g_project_setup"

	[[ -d $project_rctl ]] || mkdir -p "$project_rctl"

	if [[ ! -f $project_gitignore ]] || ! grep -E "$g_project_rctl_gitignore_grep" "$project_gitignore" >/dev/null; then
		for line in "${g_project_rctl_gitignore[@]}"; do
			echo "$line" >> "$project_gitignore"
		done
	fi

	[[ -d $project_cmd_dir ]] || mkdir "$project_cmd_dir"
	[[ -d $project_hooks_dir ]] || mkdir "$project_hooks_dir"
	[[ -d "$project_cmd_dir/local" ]] || mkdir "$project_cmd_dir/local"
	[[ -d "$project_hooks_dir/local" ]] || mkdir "$project_hooks_dir/local"
	[[ -f "$project_version" ]] || echo "$g_version_major" > "$project_version"

	if [[ ! -f $project_setup ]]; then
		touch "$project_setup"

		(
			source "$g_main_config"

			(
				echo "#"
				echo "# rctl: project general setup"
				echo "#"
				echo "# include local param (that should NOT be version controlled)"
				echo "#"
				echo
				echo "[[ -f \"\$project_rctl/param.env\" ]] || exit 1"
				echo "source \"\$project_rctl/param.env\""
				echo
				echo
				echo "#"
				echo "# Files to include and exclude in the synchronization using 'push' (space-separated)."
				echo "#"
				echo "# SYNTAX"
				echo "#     - \`\"dist\"\` will send the 'dist' directory (with its content)"
				echo "#     - \`\"dist/*\"\` will send only the content of 'dist' (not the directory itself)"
				echo "#"
				echo "# EXCLUDING"
				echo "#     - you target REMOTE files/directories, not local"
				echo "#     - e.g. \`\"dist/*.cache\"\` will only work if you included 'dist' itself"
				echo "#"
				echo
				echo "sync_include=$default_sync_include"
				echo "sync_exclude=$default_sync_exclude"
			) >> "$project_setup"
		)
	fi

	if [[ ! -f $project_param ]]; then
		touch "$project_param"

		(
			source "$g_main_config"

			(
				echo "# rctl: project local param"
				echo "#"
				echo "# PUSH CONFIG"
				echo "#     targets: list of targets"
				echo "#     target_<target>: target connection config (\"<host>\" \"<user>\" \"<target_dir>"
				echo "#"
				echo "# CUSTOM LOCAL VALUES"
				echo "#     you can add here other parameters, that will be available in your hooks and commands."
				echo "#"
				echo "# ABOUT VERSION CONTROL"
				echo "#     do not version-control this file."
				echo "#"
				echo "targets=($default_target)"
				echo "target_$default_target=($default_target_host $default_target_user $default_target_dir)"
			) >> "$project_param"

			if [[ ! -f "$project_param.dist" ]]; then
				cp "$project_param" "$project_param.dist"
			fi
		)
	fi

	echo "rctl was initialized for this project"
	echo "    use \`rctl .setup\` to edit this project general setup"
	echo "    use \`rctl .param\` to edit this project local param"
}

project_edit_setup() {
	if ! in_project; then
		throw "$err_not_project"
	fi

	edit "$(find_project_root)/$g_project_setup"
}

project_edit_param() {
	if ! in_project; then
		throw "$err_not_project"
	fi

	edit "$(find_project_root)/$g_project_param"
}

project_edit_command() {
	local cmd="$1"
	local cmd_file

	local project="$(find_project_root)"
	local project_cmd_dir="$projects/$g_project_cmd_dir"

	if ! in_project; then
		throw "$err_not_project"
	fi

	if [[ -z $cmd ]]; then
		throw "requires the command name"
	fi

	if [[ ! $cmd =~ ^[a-z_@][a-z0-9_@-]*$ ]]; then
		throw "invalid command name"
	fi

	if ! in_project; then
		throw "$err_not_project"
	fi

	cmd_file="$project_cmd_dir/$cmd.bash"

	if [[ ! -f $cmd_file ]]; then
		touch "$cmd_file"

		(
			echo '#'
			echo '# project custom command'
			echo '#     - you can call all internal functions (see `which rctl`)'
			echo '#     - you can access all internal variables'
			echo '#     - you can access your project setup'
			echo '#'
			echo
			echo 'command_run() {'
			echo '	_print "" # command parameters (summary)'
			echo '	#_print "\t" # command info'
			echo '}'
			echo
			echo 'command_usage() {'
			echo '	# parameters'
			echo '	#echo "{aaa|bbb}"'
			echo '	# details (use $_ as 1-level padding)'
			echo '	#echo "    aaa [--aaa1] -- aaa"'
			echo '	#echo "    bbb          -- bbb"'
			echo '}'
			echo
			echo 'command_autocomplete() {'
			echo '	#case "$1" in'
			echo '		#"")'
			echo '			#echo "aaa"'
			echo '			#echo "bbb"'
			echo '			#;;'
			echo '		#aaa)'
			echo '			#echo "--aaa1"'
			echo '			#'
			echo '	#esac'
			echo '}'
			echo
			echo '_throw_usage() {'
			echo '	command_usage >&2'
			echo '	exit $ERR'
			echo '}'
			echo 
			echo # print with leading indentation
			echo '_print() {'
			echo "	echo -e \"$1\"\ | perl -pe 's/\t/    /g'"
			echo '}'
			echo '		) >> $cmd_file'
			echo '	fi'
			echo
			echo '	edit "$cmd_file"'
			echo '}'
		) >> $cmd_file
	fi

	edit "$cmd_file"
}

project_edit_hook() {
	local hook="$1"
	local cmd="$(echo "$hook" | awk -F: '{ print $1 }')"
	local at="$(echo "$hook" | awk -F: '{ print $2 }')"

	local project="$(find_project_root)"
	local project_cmd_dir="$projects/$g_project_cmd_dir"

	local hook_file
	local cmd_file

	if ! in_project; then
		throw "$err_not_project"
	fi

	if [[ $at != "before" && $at != "after" ]]; then
		throw "hook moment should be 'before' or 'after'"
	fi

	if [[ -z $cmd ]]; then
		throw "requires the command name"
	fi

	if [[ ! $cmd =~ ^[a-z_@][a-z0-9_@-]*$ ]]; then
		throw "invalid command name"
	fi

	cmd_file="$project_cmd_dir/$cmd.bash"
	if [[ $cmd != "push" && $cmd != "ssh" && ! -f $cmd_file ]]; then
		throw "not a valid command"
	fi

	hook_file="$project/$g_project_hooks_dir/${cmd}.${at}.bash"

	if [[ ! -f $hook_file ]]; then
		touch "$hook_file"

		(
			echo "# project hook: $cmd:$at"
			echo "#"
			echo "# you can call all rctl functions (see \`which rctl\` source code), such as:"
			echo "#     * \`project_ssh <target> [<cmd> [<args...>]]\`"
			echo "#     * \`project_run <custom_cmd>\`"
			echo "#"
			echo "# you can access and modify all variables, such as:"
			echo "#     * \`project=\"\$project\"\` # current project root path"
			if [[ $cmd == "push" ]]; then
				echo "#     * \`sync_include=(\"\${sync_include[@]}\")\` # files to include"
				echo "#     * \`sync_exclude=(\"\${sync_exclude[@]}\")\` # files to exclude"
				echo "#     * \`rsync_opts=\"\$rsync_opts\"\` # rsync options (for example, to target -zz for older servers)"
			fi
			if [[ $cmd == "ssh" ]]; then
				echo "#     * \`ssh_opts=(\"\${ssh_opts[@]}\")\` # options for ssh (default change dir, except if args not empty)"
			fi
			if [[ $cmd == "push" || $cmd == "ssh" ]]; then
				echo "#     * \`target=\"\$target\"\` # target"
				echo "#     * \`target_host=\"\$target_host\"\` # target hostname"
				echo "#     * \`target_user=\"\$target_user\"\` # target username"
				echo "#     * \`target_dir=\"\$target_dir\"\` # target directory"
				echo "#     * \`args=(\"\${args[@]}\")\` # provided command line arguments"
			fi
			echo
			echo
		) >> $hook_file
	fi

	edit "$hook_file"
}

project_push() {
	local target="$1"; shift

	if [[ -z $target ]]; then
		throw "invalid usage"
	fi

	if ! in_project; then
		throw "$err_not_project"
	fi

	if ! project_has_target "$target"; then
		throw "target '$target' is not defined (see \`$g_rctl .param\`)"
	fi

	(
		local args=("$@")
		local project="$(find_project_root)"
		local project_rctl="$project/$g_project_rctl"
		cd "$project" # required for rsync

		source "$(find_project_root)/$g_project_setup"

		local target_full="target_$target"
		local target_host="$(eval echo \"\${$target_full[0]}\")"
		local target_user="$(eval echo \"\${$target_full[1]}\")"
		local target_dir="$(eval echo \"\${$target_full[2]}\")"

		local rsync=rsync
		local rsync_opts="$g_rsync_opts"

		run_global_hook_if_exists push "before" "$@" || return $ERR
		run_project_hook_if_exists push "before" "$@" || return $ERR

		if [[ -z $target_host || -z $target_user || -z $target_dir ]]; then
			throw "no ssh parameters found for target '$target' in param.env"
		fi

		local rsync_include=("${sync_include[@]}") # quote-enclosed, until the end
		local rsync_exclude=()

		for f in "${sync_exclude[@]}"; do
			rsync_exclude=("${rsync_exclude[@]}" --exclude="$f")
		done

		info "running push to $target"
		$rsync $g_rsync_opts ${rsync_exclude[@]} ${rsync_include[@]} -e ssh "${target_user}@${target_host}:${target_dir}"

		run_project_hook_if_exists push "after" "$@" || return $ERR
		run_global_hook_if_exists push "after" "$@" || return $ERR
	)
}

project_ssh() {
	local target="$1"; shift

	if [[ -z $target ]]; then
		throw "invalid usage"
	fi

	if ! in_project; then
		throw "$err_not_project"
	fi

	if ! project_has_target "$target"; then
		throw "target not defined (see \`$g_rctl .param\`)"
	fi

	(
		local args=("$@")
		local ssh_opts=()
		local project="$(find_project_root)"
		local project_rctl="$project/$g_project_rctl"
		cd "$project" # required for rsync

		source "$(find_project_root)/$g_project_setup"

		local target_full="target_$target"
		local target_host="$(eval echo \"\${$target_full[0]}\")"
		local target_user="$(eval echo \"\${$target_full[1]}\")"

		run_global_hook_if_exists ssh "before" "$@"
		run_project_hook_if_exists ssh "before" "$@"

		if [[ -z $target_host || -z $target_user ]]; then
			throw "no ssh parameters found for target '$target' in param.env"
		fi

		if [[ "${#args[@]}" -gt 0 ]]; then
			info "running ssh on $target"
		fi
		ssh "${target_user}@${target_host}" "${ssh_opts[@]}" "${args[@]}"

		run_project_hook_if_exists ssh "after" "$@"
		run_global_hook_if_exists ssh "after" "$@"
	)
}

project_run() {
	local cmd="$1"; shift
	local project=""
	local cmd_file
	local is_project_cmd

	if [[ ! $cmd =~ ^[a-z_@][a-z0-9_@-]*$ ]]; then
		throw "invalid command name"
	fi

	if ! in_project; then
		cmd_file="$g_main_cmd_dir/${cmd}.bash"

		if [[ ! -f $cmd_file ]]; then
			throw "invalid global command"
		fi

		run_global_hook_if_exists "$cmd" "before"

		source "$cmd_file"
		info "running global command: $cmd"
		command_run
		cmd_exit=$?

		run_global_hook_if_exists "$cmd" "after"

		exit $cmd_exit
	fi

	project="$(find_project_root)"
	project_rctl="$project/$g_project_rctl"
	project_cmd_dir="$projects/$g_project_cmd_dir"
	cmd_file="$project_cmd_dir/${cmd}.bash"
	is_project_cmd=true

	if [[ ! -f $cmd_file ]]; then
		cmd_file="$g_main_cmd_dir/${cmd}.bash"
		is_project_cmd=false

		if [[ ! -f $cmd_file ]]; then
			throw "invalid command"
		fi
	fi

	(
		cd "$project"

		source "$(find_project_root)/$g_project_setup"

		run_global_hook_if_exists "$cmd" "before"
		run_project_hook_if_exists "$cmd" "before"

		source "$cmd_file"

		if $is_project_cmd; then
			info "running project command: $cmd"
		else
			info "running global command: $cmd"
		fi

		command_run "$@"
		cmd_exit=$?

		run_project_hook_if_exists "$cmd" "after"
		run_global_hook_if_exists "$cmd" "after"

		exit $cmd_exit
	)
}


# autocomplete
#-------------------------------------------------------------------------------

autocomplete() {
	local arg="$1"; shift

	local main_cmd="$(list_commands "$g_main_cmd_dir")"
	local project="$(find_project_root "$PWD")"
	local project_rctl="$project/$g_project_rctl"
	local project_cmd=""
	local project_cmd_dir="$projects/$g_project_cmd_dir"

	if in_project; then
		project_cmd="$(list_commands "$project_cmd_dir")"
	fi

	case $arg in
		"")
			if ! in_project; then
				echo .help
			fi

			if [[ -n $main_cmd ]]; then
				for cmd in $main_cmd; do
					echo "$cmd"
				done
			fi

			if ! in_project && in_initializable_project; then
				echo init
			fi

			if in_project; then
				echo ssh
				echo push
				echo .setup
				echo .param
				echo .edit-hook
				echo .edit-cmd
				echo .help

				if [[ -n $project_cmd ]]; then
					for cmd in $project_cmd; do
						echo "$cmd"
					done
				fi
			fi
			;;

		push)
			case "$1" in
				"")
					project_list_targets
					;;
			esac
			;;

		ssh)
			case "$1" in
				"")
					project_list_targets
					;;
			esac
			;;

		.help)
			for cmd in $project_cmd; do
				echo "$cmd"
			done
			for cmd in $main_cmd; do
				echo "$cmd"
			done
			;;

		.edit-cmd)
			if [[ -n $project_cmd ]]; then
				for cmd in $project_cmd; do
					echo "$cmd"
				done
			fi
			;;

		.edit-hook)
			if [[ -z $1 ]]; then
				for cmd in push ssh ${project_cmd[@]}; do
					echo "$cmd:before"
					echo "$cmd:after"
				done
			fi
			;;

		*)
			if [[ -n $project_cmd ]]; then
				for cmd in $project_cmd; do
					if [[ $arg == $cmd ]]; then
						cmd_file="$project_cmd_dir/${cmd}.bash"
						source "$project/$g_project_setup"
						source "$cmd_file"
						command_autocomplete "$@"
					fi
				done
			fi
			;;
	esac
}


# run
#-------------------------------------------------------------------------------

main() {
	local action="$1"; shift

	if [[ $action != "---" ]]; then
		check_version
		rctl_setup
	fi

	if ! in_project && [[ $action == ".help" ]]; then
		usage
		exit $OK
	fi

	case "$action" in
		init)
			project_init
			;;

		push)
			local target="$1"; shift
			local args=("$@")

			project_push "$target" "${args[@]}" || exit $ERR
			;;

		ssh)
			local target="$1"; shift
			local args=("$@")

			project_ssh "$target" "${args[@]}"
			;;

		.setup)
			project_edit_setup
			;;

		.param)
			project_edit_parameters
			;;

		.edit-cmd)
			local cmd="$1"

			project_edit_command "$cmd"
			;;

		.edit-hook)
			local hook="$1"
			project_edit_hook "$hook"
			;;

		.help)
			usage "$@"
			;;

		---)
			autocomplete "$@"
			;;

		"")
			throw "please specify a command (see \`$g_rctl help\`)"
			;;

		*)
			project_run "$action" "$@"
			exit $?
			;;
	esac

	exit $OK
}

main "$@"
